name: tests

on:
  push:
    branches:
      - main
      - '*.x'
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [ 8.2, 8.3, 8.4 ]

    name: Run Tests – PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: ./vendor/bin/pest

  check:
    if: always()

    needs:
      - tests

    runs-on: Ubuntu-latest

    steps:
      - name: Check if all jobs are passing
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
